apiVersion: v1
kind: Namespace
metadata:
 name: nexus
ubuntu@ip-172-31-23-251:~$ cat pv-nexus.yaml 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain   # Keeps data even if PVC is deleted
  storageClassName: local-storage         # Matches your local StorageClass
  hostPath:
    path: /mnt/nexus-data                # Must exist on the node
