apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # Makes it default
provisioner: kubernetes.io/no-provisioner               # Manual provisioning
volumeBindingMode: WaitForFirstConsumer                # PV is bound when pod is scheduled
